requires 'Ark';
requires 'DateTime';
requires 'DBIx::Class', "==0.082841";
requires 'FindBin::libs';
requires 'SQL::Translator';
requires 'String::CamelCase';
requires 'Text::MicroTemplate::Extended';
requires 'Text::MicroTemplate::DataSection';
requires 'SQL::Translator';
requires 'GitDDL';
requires 'Path::Class';
requires 'DateTime::Format::SQLite';
requires 'String::CamelCase';
requires 'Data::Page::Navigation';
requires 'Cache::FastMmap';
requires 'DateTime::Format::W3CDTF';
